#ifndef IDC_STATIC
#define IDC_STATIC (-1)
#endif

#define IDD_ABOUTBOX                            100
#define IDD_TRADE                               101
#define IDD_GLASS                               102
#define IDD_LOG                                 103
#define IDD_HISTORY                             104
#define IDD_STOP                                105
#define IDD_PROPERTIES                          106
#define IDD_SETTINGS_COMMON                     111
#define IDD_SETTINGS_TRADING                    112
#define IDD_SETTINGS_INSTRUMENTS                113
#define IDD_SETTINGS_SHORTCUTS                  114
#define IDD_SETTINGS_VIEW                       115
#define IDD_SETTINGS_LIST                       116
#define IDD_SETTINGS_OSD                        117
#define IDD_SETTINGS_GLASS                      118
#define IDD_ABOUT_DESCRIPTION                   121
#define IDD_ABOUT_AUTHORS                       122
#define IDD_ABOUT_LICENCE                       123
#define IDR_MAINFRAME                           130
#define IDR_MENU_MAIN                           131
#define IDR_MENU_GLASS                          132
#define IDR_MENU_HISTORY                        133
#define IDR_MENU_HISTORY_TREE                   134
#define IDR_MENU_SHORTCUTKEYS                   135
#define IDR_MENU_LOG                            136
#define IDR_MENU_SETTINGS_TOOL                  137
#define IDR_MENU_SETTINGS_INSTRUMENT            138
#define IDR_MENU_SETTINGS_LISTOFDEALS_COLORS    139
#define IDI_UP                                  151
#define IDI_DOWN                                152
#define IDI_BUY                                 153
#define IDI_BUY_BIG                             154
#define IDI_BUY_SMALL                           155
#define IDI_SELL                                156
#define IDI_SELL_BIG                            157
#define IDI_SELL_SMALL                          158
#define IDI_BUY_GRAY                            159
#define IDI_SELL_GRAY                           160
#define IDI_ACTIVE_BUY                          161
#define IDI_ACTIVE_SELL                         162
#define IDI_CANCEL_BUY                          163
#define IDI_CANCEL_SELL                         164
#define IDI_STOP_BUY                            165
#define IDI_STOP_SELL                           166
#define IDI_ACTIVE_STOP_BUY                     167
#define IDI_ACTIVE_STOP_SELL                    168
#define IDI_STOP_BUY_GRAY                       169
#define IDI_STOP_SELL_GRAY                      170
#define IDI_CANCEL_STOP                         171
#define IDI_CANCEL_STOP_BUY                     172
#define IDI_CANCEL_STOP_SELL                    173
#define IDI_STOP                                174
#define IDI_STOP_BUY_SMALL                      175
#define IDI_STOP_SELL_SMALL                     176
#define IDI_ACTIVE_BUY_SMALL                    177
#define IDI_ACTIVE_SELL_SMALL                   178
#define IDI_GRAY_BUY_SMALL                      179
#define IDI_GRAY_SELL_SMALL                     180
#define IDI_DELETE                              181
#define IDI_SELECT                              182
#define IDI_EDIT                                183
#define IDI_NEW                                 184
#define IDI_OUTPUT                              185
#define IDI_MOVE_DOWN                           186
#define IDI_MOVE_UP                             187
#define IDI_SENT                                188
#define IDI_CANCEL                              189
#define IDI_TIME_LIST                           190
#define IDI_TOOLS                               191
#define IDI_COPY                                192
#define IDI_BUY_SELL_SMALL                      194
#define IDI_BUY_SELL_SMALL_FRAME                195
#define IDR_MENU_USER_VALUES                    197
#define IDD_BID                                 199
#define IDC_COMBO_SHORTCUTS                     1000
#define IDC_LIST_WINDOWS                        1000
#define IDC_SPIN_PRICE                          1000
#define IDC_STATIC_ALIGNMENT                    1000
#define IDC_STATIC_BUILD                        1000
#define IDC_STATIC_GLASS_MARGINS                1000
#define IDC_BUTTON_CLEAR                        1001
#define IDC_CHECKBOX1                           1001
#define IDC_CHECKBOX_GRID                       1001
#define IDC_CHECK_CANCEL_ALL_ORDERS             1001
#define IDC_STATIC_OPACITY                      1001
#define IDC_CHECKBOX_PRINT_MESSAGE_ON_TRANSACTION_ERROR 1002
#define IDC_STATIC_BUILD2                       1002
#define IDC_STATIC_OPACITY_INACTIVE             1002
#define IDC_CHECK_SHOW_USER_STOPS               1003
#define IDC_EDIT_SLIPPAGE                       1003
#define IDC_STATIC_OPACITY_ACTIVE               1003
#define IDC_LIST1                               1004
#define IDC_SPIN_OPACITY                        1004
#define IDC_SPIN_SLIPPAGE                       1004
#define IDC_CHECKBOX_USER_GROUP_BY_PRICE        1005
#define IDC_EDIT_OPACITY                        1005
#define IDC_STATIC_FRAME_GLASS_ITEM             1005
#define IDC_CHECK_NEUTRAL_ZONE                  1006
#define IDC_CHECKBOX3                           1007
#define IDC_EDIT_SPREAD                         1007
#define IDC_CHECKBOX_ENABLE_FLASHING            1008
#define IDC_COMBO_ACCOUNT                       1008
#define IDC_STATIC_WINDOW                       1009
#define IDC_COMBO_SECCODE                       1010
#define IDC_COMBO_CLASSCODE                     1011
#define IDC_COMBO_CLIENTCODE                    1012
#define IDC_EDIT_DPRICE                         1013
#define IDC_SPIN_DPRICE                         1014
#define IDC_EDIT_STOP_RELATIVE                  1015
#define IDC_BUTTON_BUY                          1016
#define IDC_SPIN_QUANTITY                       1016
#define IDC_BUTTON_SELL                         1017
#define IDC_SPIN_SPREAD                         1017
#define IDC_LIST2                               1018
#define IDC_SPIN_STOP_RELATIVE                  1018
#define IDC_EDIT_STOP_ABSOLUT                   1019
#define IDC_SPIN_STOP_ABSOLUT                   1020
#define IDC_BUTTON_STOP                         1021
#define IDC_EDIT_STOP_xQ                        1021
#define IDC_BUTTON_CANCEL                       1022
#define IDC_BUTTON_CANCEL_ALL                   1023
#define IDC_EDIT_TRADE_PRICE1                   1024
#define IDC_BUTTON_ZERO                         1025
#define IDC_BUTTON_LOG                          1026
#define IDC_BUTTON_REVERSE                      1027
#define IDC_EDIT_QUIK_PATH                      1028
#define IDC_BUTTON_QUIK_PATH                    1029
#define IDC_STATIC_PRICE                        1031
#define IDC_STATIC_QUANTITY                     1032
#define IDC_STATIC_FRAME                        1034
#define IDC_STATIC_SPREAD                       1035
#define IDC_COMBO_TYPE                          1036
#define IDC_STATIC_STOP                         1036
#define IDC_RADIO_EXPIRE_TODAY                  1037
#define IDC_STATIC_PROFIT                       1037
#define IDC_RADIO_EXPIRE_DATE                   1038
#define IDC_EXPIRE_DATE                         1039
#define IDC_RADIO_EXPIRE_GTC                    1040
#define IDC_RADIO_BUY                           1041
#define IDC_RADIO_SELL                          1042
#define IDC_RADIO_GREATER                       1043
#define IDC_RADIO_LESSER                        1044
#define IDC_EDIT_STOPPRICE                      1045
#define IDC_EDIT_PRICE                          1046
#define IDC_EDIT_QUANTITY                       1047
#define IDC_COMBO_INSTRUMENT                    1048
#define IDC_SPIN_OFFSET_X                       1049
#define IDC_SPIN_STOP_STOPPRICE                 1049
#define IDC_SPIN_OFFSET_Y                       1050
#define IDC_SPIN_STOP_QUANTITY                  1050
#define IDC_SPIN_STOP_PRICE                     1051
#define IDC_PICTURE                             1052
#define IDC_SPIN_TRADE_PRICE1                   1054
#define IDC_EDIT_TRADE_QUANTITY                 1057
#define IDC_SPIN_TRADE_QUANTITY                 1058
#define IDC_CHECK_SPREAD                        1059
#define IDC_CHECK_AUTOPRICE                     1060
#define IDC_CHECK_CONFIRM_TRANSACTION           1061
#define IDC_OSD                                 1061
#define IDC_CHECK_PRINT_TRANSACTION             1062
#define IDC_BUTTON_CLEAR_CACHE                  1063
#define IDC_EDIT_SERVER_NAME                    1064
#define IDC_COMBO1                              1065
#define IDC_EDIT_NAME                           1067
#define IDC_CHECK_KEEP_HISTORY                  1069
#define IDC_BUTTON_CLEAR_HISTORY                1070
#define IDC_BUTTON_EDIT_HISTORY                 1071
#define IDC_CHECK_HISTORY_KEEP_CANCEL           1072
#define IDC_CHECK_BEST_PRICE_IS_CURRENT_PRICE   1074
#define IDC_BUTTON_ADD                          1075
#define IDC_BUTTON_REMOVE                       1076
#define IDC_CHECK_SAVE_ON_DISK                  1076
#define IDC_BUTTON_MODIFY                       1077
#define IDC_STATIC_SERVER_STATUS                1077
#define IDC_BUTTON_SELECT                       1078
#define IDC_BUTTON_ADD_COPY                     1079
#define IDC_STATIC_SECCODE                      1080
#define IDC_STATIC_CLASSCODE                    1081
#define IDC_STATIC_CLIENTCODE                   1082
#define IDC_STATIC_ACCOUNT                      1083
#define IDC_CHECK_AUTOREGISTER_STOPORDER        1084
#define IDC_STATIC_PRICE_STEP                   1084
#define IDC_CHECK_AUTOREGISTER_STOPORDER2       1085
#define IDC_RADIO_STOP_RELATIVE                 1085
#define IDC_RADIO_STOP_ABSOLUT                  1086
#define IDC_CHECK_BUY_ABOVE                     1089
#define IDC_CHECK_SHOW_USER_BIDS                1090
#define IDC_CHECK_SHOW_USER_DEALS               1091
#define IDC_COMBO_FONT_NAME                     1094
#define IDC_COMBO_FONT_STYLE                    1095
#define IDC_COMBO_FONT_SIZE                     1096
#define IDC_CHECK_FLIP_HORIZ                    1098
#define IDC_CHECK_SHOW_USER_COL                 1099
#define IDC_CHECK_RAREFY                        1101
#define IDC_FONT_COLOR                          1105
#define IDC_EXAMPLE                             1107
#define IDC_BUTTON_BACKGROUND_COLOR             1108
#define IDC_EDIT_OFFSET_X                       1111
#define IDC_EDIT_OFFSET_Y                       1112
#define IDC_STATIC_FONT_NAME                    1113
#define IDC_STATIC_FONT_STYLE                   1114
#define IDC_STATIC_FONT_SIZE                    1115
#define IDC_STATIC_FONT_COLOR                   1116
#define IDC_STATIC_X                            1117
#define IDC_STATIC_Y                            1118
#define IDC_LIST_COLORS                         1119
#define IDC_LIST_COLUMNS                        1120
#define IDC_BUTTON_UP                           1121
#define IDC_BUTTON_DOWN                         1122
#define IDC_COLOR_BACKGROUND                    1123
#define IDC_COLOR_TEXT                          1124
#define IDC_CHECK_USE_DIFFERENT_COLORS          1125
#define IDC_CHECK_USE_DIFFERENT_COLORS_TEXT     1126
#define IDC_TREE1                               1126
#define IDC_EDIT1                               1127
#define IDC_CHECK_HISTORY_CONFIRM_REMOVE        1129
#define IDC_CHECK_MODIFY_HISTORY                1130
#define IDC_BUTTON_EXPORT                       1131
#define IDC_BUTTON_EDIT                         1132
#define IDC_BUTTON_IMPORT                       1132
#define IDC_BUTTON_RESET_SHORTCUTS              1133
#define IDC_STATIC_BACKGROUND                   1134
#define IDC_LIST_FRAME                          1135
#define IDC_STATIC_LOADING                      1136
#define IDC_SYSLINK1                            1138
#define IDC_LIST_SHORTCUTS                      1139
#define IDC_SYSLINK2                            1139
#define IDC_SYSLINK3                            1140
#define IDC_DELIMITER                           1144
#define IDC_CHECK_VERTICAL                      1145
#define IDC_HEADER                              1148
#define IDC_STATIC_TEXT                         1155
#define IDC_CHECK_ALLWAYS_ON_TOP                1157
#define IDC_DATETIMEPICKER                      1160
#define IDC_RADIO_STYLE1                        1164
#define IDC_RADIO_STYLE2                        1165
#define IDC_RADIO_STYLE3                        1166
#define IDC_STATIC_PICT1                        1167
#define IDC_STATIC_PICT2                        1168
#define IDC_STATIC_PICT3                        1169
#define IDC_COMBO_TRADING_AUTOS                 1170
#define IDC_PARAMS_SECCODE                      1171
#define IDC_COLUMN_SIZER                        1172
#define IDC_CHECK_CONFIRM_TRANSACTION_CANCEL    1173
#define IDC_CHECK_AUTO_CHECK_CONNECTION         1174
#define ID_PROPERTIES                           32777
#define ID_SETTINGS                             32790
#define ID_BUY                                  32791
#define ID_SELL                                 32792
#define ID_BUY_FIXED                            32793
#define ID_SELL_FIXED                           32794
#define ID_BUY_MARKET                           32795
#define ID_SELL_MARKET                          32796
#define ID_BUY_TA                               32797
#define ID_SELL_TA                              32798
#define ID_CANCEL_ORDER                         32801
#define ID_CANCEL_ALL_ORDERS                    32802
#define ID_CANCEL_ALL_ORDERS_BUY                32803
#define ID_CANCEL_ALL_ORDERS_SELL               32804
#define ID_CANCEL_ALL_ORDERS_STOP               32805
#define ID_CANCEL_ORDER_GLASS                   32806
#define ID_STOP_ORDER                           32809
#define ID_STOP_BID_BUY                         32810
#define ID_STOP_BID_SELL                        32811
#define ID_STOP_BID_BUY_OFFSET                  32812
#define ID_STOP_BID_SELL_OFFSET                 32813
#define ID_STOP_BID_BUY_TA                      32814
#define ID_STOP_BID_SELL_TA                     32815
#define ID_STOP_BID_BUY_OFFSET_TA               32816
#define ID_STOP_BID_SELL_OFFSET_TA              32817
#define ID_STOP_BID_TA                          32818
#define ID_SHOW_GLASS                           32825
#define ID_SHOW_MSGLOG                          32826
#define ID_SET_BASE                             32828
#define ID_SET_EXTENDED                         32829
#define ID_USER_TRADE                           32832
#define ID_TOOL_PROPERTIES                      32834
#define ID_SELECT_TOOL                          32835
#define ID_TRANSACTION_INFO                     32837
#define ID_ADD_INSTRUMENT                       32843
#define ID_REMOVE_INSTRUMENT                    32844
#define ID_SELECT_INSTRUMENT                    32845
#define ID_INSTRUMENT_PROPERTIES                32846
#define ID_XXX                                  32853
#define ID_HISTORY_LIST_REMOVE_ITEM             32855
#define ID_SHOW_HISTORY                         32858
#define ID_HISTORY_TREE_REMOVE                  32859
#define ID_REMOVE_INSTRUMENTS_ALL               32861
#define ID_EXPORT_INSTRUMENTS                   32864
#define ID_IMPORT_INSTRUMENTS                   32865
#define ID_LISTOFDEALS_COLORS_00                32869
#define ID_LISTOFDEALS_COLORS_01                32870
#define ID_LISTOFDEALS_COLORS_02                32871
#define ID_LISTOFDEALS_COLORS_03                32872
#define ID_LISTOFDEALS_COLORS_04                32873
#define ID_LISTOFDEALS_COLORS_05                32874
#define ID_LISTOFDEALS_COLORS_06                32875
#define ID_LISTOFDEALS_COLORS_07                32876
#define ID_LISTOFDEALS_COLORS_08                32877
#define ID_LISTOFDEALS_COLORS_09                32878
#define ID_LISTOFDEALS_COLORS_10                32879
#define ID_LISTOFDEALS_COLORS_11                32880
#define ID_LISTOFDEALS_COLORS_12                32881
#define ID_LISTOFDEALS_COLORS_13                32882
#define ID_LISTOFDEALS_COLORS_14                32883
#define ID_LISTOFDEALS_COLORS_15                32884
#define ID_LISTOFDEALS_COLORS_16                32885
#define ID_LISTOFDEALS_COLORS_17                32886
#define ID_LISTOFDEALS_COLORS_18                32887
#define ID_LISTOFDEALS_COLORS_19                32888
#define ID_LISTOFDEALS_COLORS_20                32889
#define ID_ABOUT                                32891
#define ID_TRADE_ZERO                           32900
#define ID_TRADE_REVERSE                        32901
#define ID_SORT_INDEX                           32921
#define ID_SORT_SIGN                            32922
#define ID_SORT_NUMBER                          32923
#define ID_SORT_DATE                            32924
#define ID_SORT_TIME                            32925
#define ID_SORT_NAME                            32926
#define ID_SORT_SECCODE                         32927
#define ID_SORT_CLASSCODE                       32928
#define ID_SORT_OPERATION                       32929
#define ID_SORT_PRICE                           32930
#define ID_SORT_PRICE2                          32931
#define ID_SORT_QUANTITY                        32932
#define ID_SORT_VOLUME                          32933
#define ID_SORT_STATUS                          32934
#define ID_SORT_CLIENTCODE                      32935
#define ID_SORT_ACCOUNT                         32936
#define ID_SORT_ASCENDING                       32937
#define ID_SORT_DESCENDING                      32938
#define ID_LOG_CLOSE                            32942
#define ID_HISTORY_TREE_EXPAND                  32946
#define ID_HISTORY_TREE_COLLAPSE                32947
#define ID_LISTOFDELAS_DEFAULT_COLOR            32949
#define ID_DEBUG_RELOADTRADE                    32951
#define ID_SHOW_LISTOFDEALS                     32957
#define ID_SHOW_OSD                             32958
#define ID_SHOW_CONTROLS                        32959
#define ID_SHOW_MAIN                            32960
#define ID_DEBUG_GETWINDOWRECT                  32961
#define ID_GLASS_STYLE_1                        32970
#define ID_GLASS_STYLE_2                        32971
#define ID_GLASS_STYLE_3                        32972
#define ID_GLASS_BUY_ABOVE                      32973
#define ID_GLASS_FLIP_HORIZONTAL                32974
#define ID_GLASS_RAREFY                         32975
#define ID_GLASS_NEUTRAL_ZONE                   32976
#define ID_USER_SHOW_ACTIVE_BIDS                32982
#define ID_USER_SHOW_ACTIVE_STOPS               32983
#define ID_USER_SHOW_ACTIVE_DEALS               32984
#define ID_USER_SHOW_ICONS                      32985
#define ID_GLASS_USER_SEPARATE_COLUMN           32990
#define ID_GLASS_USER_GROUP_PRICE               32991
#define ID_GLASS_GRID_LINES_VERTICAL            32993
#define ID_GLASS_GRID_LINES_HORIZONTAL          32994
#define ID_SHOW_TOPMOST                         32997
#define ID_ADD_INSTRUMENT_COPY                  33000
#define ID_BUY_CURRENT                          33001
#define ID_SELL_CURRENT                         33002
#define ID_SHORTCUTKEYS_EDIT                    33005
#define ID_SHORTCUTKEYS_CLEAR                   33006
#define ID_SHORTCUTKEYS_DEFAULT                 33007
#define ID_GLASS_BORDER_LINES_BORDERS           33011
#define ID_GLASS_BORDER_LINES_MEDIAN            33012
#define ID_GLASS_BORDER                         33013
#define ID_GLASS_MARKER                         33020
#define ID_GLASS_MARKER_FOLLOW_PRICE            33021
#define ID_GLASS_MARKER_FOLLOW_CURSOR           33022
#define ID_GLASS_MARKER_FOLLOW_MENU             33023
#define ID_INSTRUMENT_PREVIOS                   33040
#define ID_INSTRUMENT_NEXT                      33041
#define ID_CHANGE_ACTIVE_BID                    33051
#define IDM_PRICE1                              34001
#define IDM_PRICE2                              34002
#define IDM_PRICE3                              34003
#define IDM_PRICE4                              34004
#define IDM_PRICE5                              34005
#define IDM_PRICE6                              34006
#define IDM_PRICE7                              34007
#define IDM_PRICE8                              34008
#define IDM_PRICE9                              34009
#define IDM_PRICE10                             34010
#define IDC_SPIN2                               40038
#define IDC_EDIT_MARGINS                        40040
#define IDC_CHECKBOX_BACKGRND                   40044
#define IDC_CHECKBOX_TEXT                       40050
#define IDC_COMBO_GLASS1                        40053
#define IDC_COMBO_GLASS2                        40054
#define IDC_CHECKBOX_TEXT_1                     40057
#define IDC_CHECKBOX_BACKGRND_1                 40058
#define IDC_CHECKBOX_GRID_LINES_H               40062
#define IDC_CHECKBOX_GRID_LINES_V               40064
#define IDC_CHECK_GROUP_DIGITS                  40065
#define IDC_CHECK_SHOW_USER_ICONS               40069
#define IDC_STATIC_GLASS_BACKGRND_COLOR         40097
#define IDC_STATIC_GLASS_OPACITY                40098
#define IDC_GLASS_BACKGRND_COLOR                40099
#define IDC_GLASS_FRAME_LIST                    40102
#define IDC_GLASS_FRAME_TEXT                    40103
#define IDC_GLASS_FRAME_0                       40104
#define IDC_GLASS_FRAME_BACKGRND                40105
#define IDC_GLASS_FRAME_USER                    40106
#define IDC_GLASS_FRAME_VIEW                    40107
#define IDC_GLASS_COLOR                         40119
#define IDC_EDIT_GLASS                          40120
#define IDC_SPIN_GLASS                          40121
#define IDC_GLASS_FRAME                         40122
#define IDC_CHECKBOX_MARGINS                    40130
#define IDC_CHECKBOX_BORDER                     40131
#define IDC_CHECKBOX_MARKER                     40133
#define IDC_CHECKBOX_GLASS                      40135
#define IDC_EDIT_GLASS_BACKGRND                 40136
#define IDC_SPIN_GLASS_BACKGRND                 40137
#define IDC_STATIC_GLASS_COLOR                  40138
#define IDC_STATIC_GLASS_WIDTH                  40140
#define IDC_CHECKBOX_ALIGNMENT                  40141
#define IDC_CHECKBOX_INDICATION                 40143
#define IDC_CHECKBOX_SHOW_TITLE                 40143
#define IDC_EDIT_OPACITY2                       40144
#define IDC_SPIN_OPACITY2                       40145
#define IDC_CHECK_SHOW_CONTROLS                 40148
#define IDC_CHECK_SHOW_OSD                      40149
#define IDC_CHECK_SHOW_LISTOFDEALS              40150
#define IDC_CHECK_SHOW_FRAME_CONTROLS           40152
#define IDC_CHECK_SHOW_FRAME_OSD                40153
#define IDC_CHECK_SHOW_FRAME_LISTOFDEALS        40154
