/*
 *  Copyright (C) 2010 Alexander Chernykh 
 *
 *  This file is part of MyQuik: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  MyQuik is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 *
 *  strings.h
 */

#pragma once

extern LPCTSTR STRING_BUY;
extern LPCTSTR STRING_SELL;
extern LPCTSTR STRING_BUY_FIXED;
extern LPCTSTR STRING_SELL_FIXED;
extern LPCTSTR STRING_BUY_MARKET;
extern LPCTSTR STRING_SELL_MARKET;
extern LPCTSTR STRING_BUY_CURRENT;
extern LPCTSTR STRING_SELL_CURRENT;
extern LPCTSTR STRING_BUY_TA;
extern LPCTSTR STRING_SELL_TA;
extern LPCTSTR STRING_CANCEL_BID;
extern LPCTSTR STRING_CANCEL_ALL;
extern LPCTSTR STRING_CANCEL_ALL_BUY;
extern LPCTSTR STRING_CANCEL_ALL_SELL;
extern LPCTSTR STRING_CANCEL_ALL_STOPS;
extern LPCTSTR STRING_CHANGE_BID;
extern LPCTSTR STRING_CHANGE_STOP_BID;
extern LPCTSTR STRING_TRADE_ZERO;
extern LPCTSTR STRING_TRADE_REVERSE;
extern LPCTSTR STRING_STOP_ORDER;
extern LPCTSTR STRING_STOP_ORDER_;
extern LPCTSTR STRING_STOP_BID_BUY;
extern LPCTSTR STRING_STOP_BID_SELL;
extern LPCTSTR STRING_STOP_BID_BUY_OFFSET;
extern LPCTSTR STRING_STOP_BID_SELL_OFFSET;
extern LPCTSTR STRING_STOP_BID_BUY_TA;
extern LPCTSTR STRING_STOP_BID_SELL_TA;
extern LPCTSTR STRING_STOP_BID_BUY_OFFSET_TA;
extern LPCTSTR STRING_STOP_BID_SELL_OFFSET_TA;
extern LPCTSTR STRING_STOP_BID_TA;

extern LPCTSTR STRING_TRANSACTION_INFO;
extern LPCTSTR STRING_ACTIVE_BIDSNDEALS;

extern LPCTSTR STRING_INSTRUMENT;
extern LPCTSTR STRING_PROPERTIES;

extern LPCTSTR STRING_WND_DEALS;
extern LPCTSTR STRING_WND_GLASS;
extern LPCTSTR STRING_WND_QUOTES;
extern LPCTSTR STRING_WND_HISTORY;
extern LPCTSTR STRING_WND_MSGLOG;

extern LPCTSTR STRING_TOPMOST;

extern LPCTSTR STRING_LISTOFDEALS;
extern LPCTSTR STRING_OSD;
extern LPCTSTR STRING_CONTROLS;

extern LPCTSTR STRING_KEYS_SET_BASIC;
extern LPCTSTR STRING_KEYS_SET_EXT;

extern LPCTSTR STRING_ABOUT;

extern LPCTSTR STRING_GLASS_VIEW;
#if 0
extern LPCTSTR STRING_GLASS_STYLE_1;
extern LPCTSTR STRING_GLASS_STYLE_2;
extern LPCTSTR STRING_GLASS_STYLE_3;
extern LPCTSTR STRING_GLASS_BUY_ABOVE;
extern LPCTSTR STRING_GLASS_FLIP_HORIZONTAL;
extern LPCTSTR STRING_GLASS_RAREFY;
extern LPCTSTR STRING_GLASS_USER_SEPARATE_COLUMN;
#endif

extern LPCTSTR STRING_DEALS_VIEW;
